In [1]:
import math

def derivate(x):
  return 2* x * math.cos(x**2)
print(derivate(2))

-2.6145744834544478


In [2]:
import torch

In [3]:
x=torch.tensor(3.0,requires_grad=True)

In [4]:
y=x**2

In [5]:
x

tensor(3., requires_grad=True)

In [6]:
y

tensor(9., grad_fn=<PowBackward0>)

In [7]:
y.backward()

In [8]:
x.grad

tensor(6.)

In [9]:
x=torch.tensor(4.0,requires_grad=True)


In [10]:
y=x**2



In [11]:
z=torch.sin(y)

In [12]:
z.backward()

In [13]:
x.grad

tensor(-7.6613)

In [14]:
y.grad

/tmp/ipython-input-486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [15]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)
w=torch.tensor(1.0)
b=torch.tensor(0.0)


In [16]:
def loss_func(predication,target):
  epsilon=1e-8
  predication=torch.clamp(predication,epsilon,1-epsilon)
  return -(target*torch.log(predication)+(1-target)*torch.log(1-predication))

In [17]:
z=w*x+b
y_pred=torch.sigmoid(z)

loss=loss_func(y_pred,y)
loss

tensor(6.7012)

In [20]:
#derivatives
dloss_d_pred=(y_pred - y)/ (y_pred*(1-y_pred))

d_pred_d_z= y_pred*(1-y_pred)

dloss_dw=x
dloss_db=1

dl_dw= dloss_d_pred* d_pred_d_z* dloss_dw
dl_db= dloss_d_pred* d_pred_d_z* dloss_db

print(f"Manual Gradient of loss w.r.t weight (dw): {dl_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dl_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [21]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)


In [22]:
w,b

(tensor(1., requires_grad=True), tensor(0., requires_grad=True))

In [24]:
z=w*x +b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [25]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [26]:
loss=loss_func(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [27]:
loss.backward()

In [29]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [46]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [55]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [56]:
y.backward()

In [57]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [58]:
x.grad.zero_()

tensor([0., 0., 0.])

In [59]:
x=torch.tensor(3.0,requires_grad=True)

In [67]:
with torch.no_grad():
  y=x**2

In [68]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [70]:
# with torch.no_grad():
y=x**2

In [71]:
y.backward()

In [72]:
x.grad

tensor(12.)