In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
X,y=make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_classes=2,
    n_redundant=0,
    random_state=42
)

In [57]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [9]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [11]:
from torch.utils.data import DataLoader,Dataset

In [13]:
class CustomDataset(Dataset):

  def __init__(self,featrues,labels):
    self.featrues=featrues
    self.labels=labels

  def __len__(self):
    return self.featrues.shape[0]

  def __getitem__(self,index):
    return self.featrues[index],self.labels[index]

In [14]:
dataset=CustomDataset(X,y)

In [15]:
len(dataset)

10

In [16]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [36]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [37]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-0.5872, -1.9717],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------


In [40]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [47]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
249    884689         B        11.52         14.93           73.87      406.3   
383     90251         B        12.39         17.48           80.64      462.9   
451   9111805         M        19.59         25.00          127.70     1191.0   
147  86973701         B        14.95         18.77           97.84      689.5   
445   9110720         B        11.99         24.89           77.61      441.3   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
249          0.10130           0.07808         0.04328              0.02929   
383          0.10420           0.12970         0.05892              0.02880   
451          0.10320           0.09871         0.16550              0.09063   
147          0.08138           0.11670         0.09050              0.03562   
445          0.10300           0.09218         0.05441              0.04274   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
249  ...          21.19            80.88       491.8            0.1389   
383  ...          23.13            95.23       600.5            0.1427   
451  ...          30.96           139.80      1421.0            0.1528   
147  ...          25.47           107.10       809.7            0.0997   
445  ...          30.36            84.48       513.9            0.1311   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
249             0.1582           0.1804               0.09608          0.2664   
383             0.3593           0.3206               0.09804          0.2819   
451             0.1845           0.3977               0.14660          0.2293   
147             0.2521           0.2500               0.08405          0.2852   
445             0.1822           0.1609               0.12020          0.2599   

     fractal_dimension_worst  Unnamed: 32  
249                  0.07809          NaN  
383                  0.11180          NaN  
451                  0.06091          NaN  
147                  0.09218          NaN  
445                  0.08251          NaN  

[5 rows x 33 columns]

In [42]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [59]:
X_train.shape

(455, 32)

In [44]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [46]:
y_train

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,

In [52]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [53]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [54]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [64]:
train_dataset[10]


(tensor([ 1.2401, -0.1169,  1.1748,  1.1427,  0.0788,  0.1419,  0.3163,  0.8298,
         -0.0598, -0.9013,  0.0364, -1.2184, -0.1332,  0.2549, -0.7610, -0.5136,
         -0.2652, -0.0698, -0.9853, -0.5316,  1.2267, -0.1159,  1.0719,  1.1344,
          0.4733,  0.1304,  0.5242,  0.9807, -0.1600, -0.1391]),
 tensor(1.))

In [68]:
len(train_dataset)

455

In [69]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [70]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [71]:
learning_rate = 0.1
epochs = 25

In [73]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [74]:
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.08613882958889008
Epoch: 2, Loss: 0.08429784327745438
Epoch: 3, Loss: 0.10212462395429611
Epoch: 4, Loss: 0.03359265252947807
Epoch: 5, Loss: 0.05174604058265686
Epoch: 6, Loss: 0.04349078983068466
Epoch: 7, Loss: 0.047153111547231674
Epoch: 8, Loss: 0.025031892582774162
Epoch: 9, Loss: 0.04157993942499161
Epoch: 10, Loss: 0.06799686700105667
Epoch: 11, Loss: 0.01775173470377922
Epoch: 12, Loss: 0.1074870303273201
Epoch: 13, Loss: 0.10095322132110596
Epoch: 14, Loss: 0.0660807341337204
Epoch: 15, Loss: 0.04013032466173172
Epoch: 16, Loss: 0.009812985546886921
Epoch: 17, Loss: 0.04332345724105835
Epoch: 18, Loss: 0.0014032676117494702
Epoch: 19, Loss: 0.11166709661483765
Epoch: 20, Loss: 0.6764863729476929
Epoch: 21, Loss: 0.09429492056369781
Epoch: 22, Loss: 0.01029946468770504
Epoch: 23, Loss: 0.007372475694864988
Epoch: 24, Loss: 0.00798017904162407
Epoch: 25, Loss: 0.12468699365854263


In [75]:
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.8976
