In [29]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler


In [30]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [31]:
df.shape

(569, 33)

In [32]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [33]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [34]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [35]:
X_test


array([[-0.50455172,  1.75813162, -0.44140726, ...,  0.48006879,
         0.51541319,  2.05859273],
       [-1.56556381,  0.39116087, -1.52940383, ..., -1.3358783 ,
         0.12160871, -0.37369249],
       [ 1.33279685,  0.62131411,  1.30620519, ...,  0.86287511,
         0.17832952, -0.03615544],
       ...,
       [ 0.60976616,  0.32839181,  0.61619604, ...,  0.67070326,
         0.3339066 , -0.10007442],
       [-1.35716085,  0.61433977, -1.35074075, ..., -1.36877812,
        -0.74865059, -0.55255348],
       [-0.793764  ,  1.80927678, -0.82707309, ..., -1.44272584,
        -0.07772443, -0.72412547]])

In [36]:
y_train

102    B
123    B
386    B
306    B
165    B
      ..
101    B
77     M
417    M
424    B
212    M
Name: diagnosis, Length: 455, dtype: object

In [37]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [38]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,

In [39]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [40]:
X_train_tensor

tensor([[-0.5499,  0.2842, -0.6028,  ..., -0.6205, -0.3289, -0.8413],
        [ 0.1079, -1.9545,  0.0979,  ...,  0.1142, -0.0129, -0.2088],
        [-0.5414, -1.2106, -0.5387,  ..., -0.3578, -0.3565,  0.2498],
        ...,
        [ 0.3914,  0.4144,  0.4519,  ...,  1.5178,  0.1718,  1.1783],
        [-1.2412, -0.0412, -1.2308,  ..., -1.0575,  0.4846, -0.2072],
        [ 3.9669, -0.1924,  3.9677,  ...,  0.6892, -2.0241, -1.5999]],
       dtype=torch.float64)

In [41]:
X_train_tensor.shape

torch.Size([455, 30])

In [42]:
y_train_tensor.shape

torch.Size([455])

In [73]:
import torch.nn as nn
class NeuralNetwork(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):

    out=self.linear(features)
    out=self.sigmoid(out)
    return out


In [74]:

learning_rate=0.5
epochs=50

In [75]:
loss_func=nn.BCELoss()

In [76]:
#create model
model=NeuralNetwork(X_train_tensor.shape[1])
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
# define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model(X_train_tensor.float())

  #loss calculate
  loss=loss_func(y_pred,y_train_tensor.view(-1,1).float())

  #clear gradients
  optimizer.zero_grad()
  #back pass
  loss.backward()

  #update parameters
  optimizer.step()
  #loss in each epcoh
  print(f'epoch :{epoch+1},Loss: {loss.item()}')

epoch :1,Loss: 0.8601138591766357
epoch :2,Loss: 0.23288333415985107
epoch :3,Loss: 0.20148944854736328
epoch :4,Loss: 0.18063542246818542
epoch :5,Loss: 0.16592538356781006
epoch :6,Loss: 0.1550113707780838
epoch :7,Loss: 0.14652898907661438
epoch :8,Loss: 0.13968674838542938
epoch :9,Loss: 0.13401079177856445
epoch :10,Loss: 0.12920072674751282
epoch :11,Loss: 0.12505552172660828
epoch :12,Loss: 0.12143445760011673
epoch :13,Loss: 0.1182355284690857
epoch :14,Loss: 0.11538263410329819
epoch :15,Loss: 0.11281765252351761
epoch :16,Loss: 0.11049524694681168
epoch :17,Loss: 0.10837950557470322
epoch :18,Loss: 0.10644153505563736
epoch :19,Loss: 0.10465776920318604
epoch :20,Loss: 0.10300882160663605
epoch :21,Loss: 0.1014784723520279
epoch :22,Loss: 0.10005320608615875
epoch :23,Loss: 0.09872143715620041
epoch :24,Loss: 0.09747336804866791
epoch :25,Loss: 0.09630054235458374
epoch :26,Loss: 0.09519565850496292
epoch :27,Loss: 0.09415234625339508
epoch :28,Loss: 0.09316503256559372
epoch

In [67]:
model.linear.bias

Parameter containing:
tensor([-0.4943], requires_grad=True)

In [68]:
model.linear.weight



Parameter containing:
tensor([[ 0.3834,  0.4132,  0.4254,  0.6344,  0.0822, -0.0132,  0.4139,  0.6389,
          0.2309, -0.3442,  0.6690,  0.0987,  0.3579,  0.2876,  0.0640, -0.2195,
         -0.0892,  0.0489, -0.2116, -0.2134,  0.6585,  0.5389,  0.6301,  0.5781,
          0.5078,  0.1485,  0.4257,  0.5280,  0.3545,  0.2610]],
       requires_grad=True)

In [79]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor.float())
  y_pred=(y_pred>0.9).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5277008414268494
