In [18]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):

      super().__init__()
      self.linear=nn.Linear(num_features,1)
      self.sigmoid=nn.Sigmoid()


    def forward(self,features):

      out=self.linear(features)
      out=self.sigmoid(out)

      return out



In [19]:
features=torch.rand(10,5)

model=Model(features.shape[1])

model(features)

tensor([[0.4981],
        [0.4642],
        [0.5237],
        [0.4823],
        [0.5867],
        [0.5314],
        [0.4362],
        [0.5589],
        [0.5808],
        [0.5029]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear.weight

Parameter containing:
tensor([[ 0.1849,  0.3640, -0.0011,  0.4084, -0.2396]], requires_grad=True)

In [21]:
model.linear.bias

Parameter containing:
tensor([-0.2427], requires_grad=True)

In [22]:
!pip install torchinfo

In [23]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [29]:
import torch
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):

      super().__init__()
      self.linear1=nn.Linear(num_features,3)
      self.relu=nn.ReLU()
      self.linear2=nn.Linear(3,1)
      self.sigmoid=nn.Sigmoid()


    def forward(self,features):

      out=self.linear1(features)
      out=self.relu(out)
      out=self.linear2(out)
      out=self.sigmoid(out)

      return out

In [32]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)


tensor([[0.6091],
        [0.6091],
        [0.6091],
        [0.6115],
        [0.6123],
        [0.6139],
        [0.6188],
        [0.6091],
        [0.6038],
        [0.6091]], grad_fn=<SigmoidBackward0>)

In [33]:
class Model(nn.Module):
    def __init__(self,num_features):

      super().__init__()
      self.network=nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
      )

    def forward(self,features):

      out=self.network(features)

      return out

In [34]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)


tensor([[0.5867],
        [0.5867],
        [0.5827],
        [0.5825],
        [0.5867],
        [0.5867],
        [0.5867],
        [0.5867],
        [0.5867],
        [0.5867]], grad_fn=<SigmoidBackward0>)