In [70]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler


In [71]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [72]:
df.shape

(569, 33)

In [73]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [74]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [75]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [76]:
X_test


array([[-0.99415803, -0.21673014, -1.01840483, ..., -1.38466953,
        -0.31464554, -0.93300364],
       [-0.39344736, -1.60700364, -0.44400878, ..., -0.47702565,
        -0.19240024,  0.63456836],
       [-0.64444853, -0.42696662, -0.67319525, ..., -1.06951961,
         0.49120833, -1.02494334],
       ...,
       [-1.19806123, -0.81353047, -1.17446407, ..., -0.73350083,
        -0.63151822,  0.48803945],
       [-0.08322119, -0.78866379, -0.05386068, ...,  0.37073369,
        -0.49157952,  1.11495333],
       [-0.1509069 , -1.21591857, -0.12903058, ..., -0.34606604,
         0.27406208, -0.10497165]])

In [77]:
y_train

167    M
343    M
192    B
492    M
147    B
      ..
27     M
245    B
21     B
118    M
161    M
Name: diagnosis, Length: 455, dtype: object

In [78]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [79]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,

In [80]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [81]:
X_train_tensor

tensor([[ 0.7572, -0.1082,  0.7170,  ...,  0.5083, -0.1361, -0.6503],
        [ 1.5751,  0.5428,  1.5586,  ...,  1.6894,  1.8504, -0.2538],
        [-1.2339, -0.2393, -1.2672,  ..., -1.7207, -1.5854, -1.0347],
        ...,
        [-1.2948, -1.5460, -1.2831,  ..., -0.7790, -0.7152, -0.3371],
        [ 0.4752,  0.8209,  0.5700,  ...,  1.3552,  0.6102,  2.3906],
        [ 1.4369, -0.7548,  1.4115,  ...,  0.9666, -0.7264, -1.2117]],
       dtype=torch.float64)

In [82]:
X_train_tensor.shape

torch.Size([455, 30])

In [83]:
y_train_tensor.shape

torch.Size([455])

In [110]:
class NeuralNetwork():

  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bais=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+ self.bais
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_func(self,y_pred,y):
    epsilon=1e-8
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred)+(1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [148]:

learning_rate=0.5
epochs=50

In [149]:
#create model
model=NeuralNetwork(X_train_tensor)
# define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_func(y_pred,y_train_tensor)

  #back pass
  loss.backward()

  #update parameters
  with torch.no_grad():
    model.weights-=learning_rate * model.weights.grad
    model.bais-=learning_rate * model.bais.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bais.grad.zero_()

  #loss in each epcoh
  print(f'epoch :{epoch+1},Loss: {loss.item()}')


epoch :1,Loss: 3.667894703904088
epoch :2,Loss: 2.923591066516788
epoch :3,Loss: 2.0880006217060716
epoch :4,Loss: 1.3472471652856464
epoch :5,Loss: 0.9058876505925059
epoch :6,Loss: 0.8135731298287031
epoch :7,Loss: 0.7668937740232781
epoch :8,Loss: 0.7353519041796263
epoch :9,Loss: 0.71440812602302
epoch :10,Loss: 0.700714935997704
epoch :11,Loss: 0.6917600635542137
epoch :12,Loss: 0.6857981103273586
epoch :13,Loss: 0.6817004821284693
epoch :14,Loss: 0.6787711117388133
epoch :15,Loss: 0.676589950706575
epoch :16,Loss: 0.674903481936312
epoch :17,Loss: 0.6735561831784744
epoch :18,Loss: 0.6724500450055223
epoch :19,Loss: 0.6715212663774978
epoch :20,Loss: 0.6707268832163817
epoch :21,Loss: 0.6700370092274104
epoch :22,Loss: 0.6694302346700272
epoch :23,Loss: 0.6688908206504826
epoch :24,Loss: 0.6684069342161181
epoch :25,Loss: 0.6679695028777695
epoch :26,Loss: 0.6675714489025191
epoch :27,Loss: 0.6672071638068237
epoch :28,Loss: 0.6668721393836147
epoch :29,Loss: 0.6665627035741521
e

In [150]:
model.bais

tensor([-0.5390], dtype=torch.float64, requires_grad=True)

In [151]:
model.weights


tensor([[-0.0712],
        [ 0.0907],
        [ 0.2954],
        [ 0.4657],
        [ 0.0201],
        [ 0.0202],
        [ 0.1202],
        [-0.1819],
        [-0.0586],
        [-0.0799],
        [ 0.1263],
        [-0.0048],
        [ 0.1271],
        [-0.1493],
        [ 0.0450],
        [-0.3734],
        [-0.0302],
        [ 0.0263],
        [-0.0098],
        [ 0.1583],
        [-0.2671],
        [-0.0821],
        [-0.2884],
        [-0.2584],
        [-0.0404],
        [ 0.3453],
        [-0.0075],
        [ 0.0269],
        [ 0.0458],
        [-0.0130]], dtype=torch.float64, requires_grad=True)

In [159]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.6).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.6140350699424744
