In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [ ]:
a= torch.empty(2,3,dtype=torch.int32)

In [ ]:
a

tensor([[-1.2850e-27,  4.3341e-41,  8.6447e+03],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.1694, 0.9075, 0.0590],
        [0.3689, 0.4795, 0.1624]])

In [ ]:
X=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
X.shape

torch.Size([2, 3])

In [ ]:
torch.full((3,4),7)

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])

In [ ]:
torch.manual_seed(112)
torch.rand(2,3)

tensor([[0.0146, 0.1393, 0.9180],
        [0.3637, 0.2042, 0.6238]])

In [ ]:
torch.manual_seed(112)
torch.rand(3,3)

tensor([[0.0146, 0.1393, 0.9180],
        [0.3637, 0.2042, 0.6238],
        [0.3734, 0.9844, 0.8940]])

In [ ]:
torch.arange(0,12,3)

tensor([0, 3, 6, 9])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [ ]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand_like(a,dtype=torch.float32)

tensor([[0.0146, 0.1393, 0.9180],
        [0.3637, 0.2042, 0.6238]])

In [ ]:
torch.manual_seed(112)
torch.empty_like(a)

tensor([[1.0682e+04, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 4.4842e-44]])

In [ ]:
a.dtype

torch.float32

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.1829, 0.6861],
        [0.0303, 0.1681]])

In [ ]:
x+2
x**2

tensor([[0.0335, 0.4708],
        [0.0009, 0.0283]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3156, 0.9312, 0.9074],
        [0.8470, 0.8995, 0.0910]])
tensor([[0.0753, 0.0427, 0.7949],
        [0.4203, 0.5299, 0.6061]])


In [ ]:
a*b

tensor([[0.0238, 0.0398, 0.7213],
        [0.3560, 0.4766, 0.0552]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
abs(c)

tensor([1, 2, 3, 4])

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
e

tensor([[0., 7., 7.],
        [7., 8., 0.]])

In [ ]:
torch.sum(e, dim=1)
torch.sum(e,dim=0)
torch.sum(e)

tensor(29.)

In [ ]:
torch.mean(e)
torch.mean(e,dim=0)
torch.mean(e,dim=1)

tensor([4.6667, 5.0000])

In [ ]:
torch.median(e,dim=0)

torch.return_types.median(
values=tensor([0., 7., 0.]),
indices=tensor([0, 0, 1]))

In [ ]:
torch.min(e)
torch.max(e)

tensor(8.)

In [ ]:
torch.prod(e)
torch.prod(e,dim=1)
torch.prod(e,dim=0)

tensor([ 0., 56.,  0.])

In [ ]:
torch.std(e)

tensor(3.7639)

In [ ]:
torch.var(e,dim=1)
torch.var(e)

tensor(14.1667)

In [ ]:
torch.argmax(e)

tensor(4)

In [ ]:
torch.argmin(e)

tensor(0)

In [ ]:
f = torch.randint(size=(3,3), low=0, high=10)
g = torch.randint(size=(3,3), low=0, high=10)

print(f)
print(g)


tensor([[5, 3, 8],
        [3, 0, 7],
        [3, 7, 4]])
tensor([[7, 2, 8],
        [2, 5, 5],
        [9, 3, 2]])


In [ ]:
torch.matmul(f,g)

tensor([[113,  49,  71],
        [ 84,  27,  38],
        [ 71,  53,  67]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
torch.transpose(f, 0, 1)

tensor([[5, 3, 3],
        [3, 0, 7],
        [8, 7, 4]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 9., 0.],
        [9., 9., 0.],
        [1., 4., 1.]])

In [ ]:
torch.det(h)

tensor(-63.)

In [ ]:
torch.inverse(h)

tensor([[-0.1429,  0.1429,  0.0000],
        [ 0.1429, -0.0317,  0.0000],
        [-0.4286, -0.0159,  1.0000]])

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 4, 7],
        [8, 2, 2]])
tensor([[6, 7, 2],
        [4, 4, 2]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

tensor([[ True,  True,  True],
        [ True,  True, False]])

In [ ]:
a=torch.rand(2,3)
a


tensor([[0.6160, 0.9612, 0.9433],
        [0.9012, 0.7583, 0.5295]])

In [ ]:
b=a

In [ ]:
a[0][0]=1

In [ ]:
a


tensor([[1.0000, 0.9612, 0.9433],
        [0.9012, 0.7583, 0.5295]])

In [ ]:
b

tensor([[1.0000, 0.9612, 0.9433],
        [0.9012, 0.7583, 0.5295]])

In [ ]:
b=a.clone()

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.9612, 0.9433],
        [0.9012, 0.7583, 0.5295]])

In [ ]:
b

tensor([[1.0000, 0.9612, 0.9433],
        [0.9012, 0.7583, 0.5295]])

In [ ]:
id(a)

132837303872752

In [ ]:
id(b)

132837302584528

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
torch.rand(2,3,device=device)

tensor([[0.5952, 0.5377, 0.4878],
        [0.4607, 0.1479, 0.1820]], device='cuda:0')

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.6643, 0.3390, 0.4412],
        [0.7076, 0.2799, 0.0897]])

In [11]:
b=a.to(device)

In [14]:
b+5

tensor([[5.6643, 5.3390, 5.4412],
        [5.7076, 5.2799, 5.0897]], device='cuda:0')

In [17]:
import time

size=10000

matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)

cpu_time=time.time()-start_time

print(f"CPU time:{cpu_time:.4f} seconds")

matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time

print(f"GPU time:{gpu_time:.4f} seconds")
print("\n speedup (CPU time/GPU time):",cpu_time/gpu_time)

CPU time:24.4908 seconds
GPU time:0.5452 seconds

 speedup (CPU time/GPU time): 44.923276681684555


In [23]:
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [50]:
d=torch.rand(1,20)
d

tensor([[0.7876, 0.6121, 0.9769, 0.9601, 0.7629, 0.1499, 0.6799, 0.6814, 0.1688,
         0.0675, 0.2500, 0.3514, 0.3093, 0.1261, 0.9369, 0.1187, 0.8510, 0.5859,
         0.6497, 0.3641]])

In [54]:
e=d.squeeze(0)
e.shape

torch.Size([20])

In [55]:
import numpy as np
a=torch.tensor([1,2,43])

In [57]:
type(a)

torch.Tensor

In [56]:
b=a.numpy()

In [59]:
type(b)

numpy.ndarray

In [60]:
d=np.array([1,2,3])

In [63]:
f=torch.from_numpy(d)
f

tensor([1, 2, 3])

In [64]:
type(f)

torch.Tensor